                               <ul>
                                    <li>Details
                                        <ul>
                                            <li><a href="AptDetailsView.html">View Details</a></li>
                                        </ul>
                                    </li>
                                    <li>Flat Details
                                        <ul>
                                            <li><a href="#">View Details</a></li>
                                            <li><a href="#">Manage Flats</a></li>
                                        </ul>
                                    </li>
                                    <li>Asset
                                        <ul>
                                            <li><a href="#">View Asset</a></li>
                                            <li><a href="#">Add Asset</a></li>
                                        </ul>
                                    </li>
                                    <li>Monthly Charges
                                        <ul>
                                            <li><a href="#">View Details</a></li>
                                            <li><a href="#">Add Details</a></li>
                                        </ul>
                                    </li>
                                    <li>Common Rentals
                                        <ul>
                                            <li><a href="#">View Details</a></li>
                                            <li><a href="#">Add Details</a></li>
                                        </ul>
                                    </li>
                                    <li>Calculation
                                        <ul>
                                            <li><a href="#">View Calcuation Setup</a></li>
                                            <li><a href="#">Add Calcuation Setup</a></li>
                                        </ul>
                                    </li>
                              </ul>
