                    <div>
                    	<ul id="nav">
                           <li class="top"><a class="top_link" href="#"><span class="down">Admin</span></a>
                                <ul class="sub">
					<li><a href="#" class="fly">User Management</a>
						<ul>
							<li><a href="ListAllUsers.html">View User </a></li>
							<li><a href="CreateUser.html">Add User </a></li>
						</ul>
					</li>
					<li><a href="#" class="fly">Masters</a>
						<ul>
							<li><a href="ListAllMasters.html">View Masters</a></li>
							<li><a href="CreateMasters.html">Add Masters</a></li>
							<li><a href="ListAllFeedFormats.html">Feed Format</a></li>
							<li><a href="ListAllFeedSch.html">Schedule Feed Upload</a></li>
						</ul>
					</li>
					<li><a href="#" class="fly">Template</a>
						<ul>
						    <li><a href="#">Bill Template</a></li>
						    <li><a href="#">Meeting Request</a></li>
						    <li><a href="#">Meeting Minutes</a></li>
						</ul>
					</li>
                            	</ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">Apartment</span></a>
				<ul class="sub">
                                    <li><a href="#" class="fly">Details</a>
                                        <ul>
                                            <li><a href="AptDetailsView.html">View Details</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Flat Details</a>
                                        <ul>
                                            <li><a href="#">View Details</a></li>
                                            <li><a href="#">Manage Flats</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Asset</a>
                                        <ul>
                                            <li><a href="#">View Asset</a></li>
                                            <li><a href="#">Add Asset</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Monthly Charges</a>
                                        <ul>
                                            <li><a href="#">View Details</a></li>
                                            <li><a href="#">Add Details</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Common Rentals</a>
                                        <ul>
                                            <li><a href="#">View Details</a></li>
                                            <li><a href="#">Add Details</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Calculation</a>
                                        <ul>
                                            <li><a href="#">View Calcuation Setup</a></li>
                                            <li><a href="#">Add Calcuation Setup</a></li>
                                        </ul>
                                    </li>
                               	</ul>
                             </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">Info Center</span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">Memo's</a>
                                        <ul>
                                            <li><a href="#">View Memo's</a></li>
                                            <li><a href="#">Add Memo's</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Meeting Minutes</a>
                                        <ul>
						<li><a href="#">View Minutes</a></li>
						<li><a href="#">Add Minutes</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">General Info</a>
                                        <ul>
						<li><a href="#">View Apartment Details</a></li>
						<li><a href="#">Add General Info</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">Work List</span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">Bills & Letters</a>
                                        <ul>
                                            <li><a href="#">View History</a></li>
                                            <li><a href="#">Clearance Certificate</a></li>
                                            <li><a href="#">Payment Entry</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Meeting</a>
                                        <ul>
                                            <li><a href="#">View Meeting Minutes</a></li>
                                            <li><a href="#">Add Meeting Request</a></li>
                                            <li><a href="#">Add Meeting Minutes</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">Request</span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">Meeting</a>
                                        <ul>
                                            <li><a href="#">View Request</a></li>
                                            <li><a href="#">Initiation Request</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Retal</a>
                                        <ul>
                                            <li><a href="#">View Rental</a></li>
                                            <li><a href="#">Raise Rental Request</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">My Portfolio</span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">My Details</a>
                                        <ul>
                                            <li><a href="#">View Details</a></li>
                                            <li><a href="#">Add details</a></li>
                                            <li><a href="#">View Contact</a></li>
                                            <li><a href="#">Add Contact</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Flat Details</a>
                                        <ul>
                                            <li><a href="#">View Details</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Payment</a>
                                        <ul>
                                            <li><a href="#">View Payment</a></li>
                                            <li><a href="#">Add Payment Details</a></li>
                                            <li><a href="#">Pay Online</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">Entry Register</span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">Guest</a>
                                        <ul>
                                            <li><a href="#">View Guest Entry</a></li>
                                            <li><a href="#">Add Guest Entry</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Material</a>
                                        <ul>
                                            <li><a href="#">View Material Entry</a></li>
                                            <li><a href="#">Add Material Entry</a></li>
                                            <li><a href="#">Add Vehicle Entry</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Staff</a>
                                        <ul>
                                            <li><a href="#">View Staff Entry</a></li>
                                            <li><a href="#">Add Staff Entry</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">Inbox</span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">Request</a>
                                        <ul>
                                            <li><a href="#">View Meeting Request</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Reminders</a>
                                        <ul>
                                            <li><a href="#">View Payment Reminders</a></li>
                                            <li><a href="#">View Tax Reminders</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">Reports</span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">Expenses</a>
                                        <ul>
                                            <li><a href="#">Expense Report</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Payment</a>
                                        <ul>
                                            <li><a href="#">Payment Report</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Regulatory </a>
                                        <ul>
                                            <li><a href="#">Regulatory Report</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>