                    <div>
                    	<ul id="nav">
                           <li class="top"><a class="top_link" href="#"><span class="down">ADMINISTRATION</span></a>
                                <ul class="sub">
				<li><a href="#" class="fly">User Management</a>
					<ul>
						<li><a href="ListAllUsers.html">View User </a></li>
						<li><a href="CreateUser.html">Add User </a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Roles Management</a>
					<ul>
						<li><a href="ListAllRoles.html">View Roles</a></li>
						<li><a href="AddRoles.html">Create Roles</a></li>
						 <li><a href="AssignedUsers.html">Assigned Users</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Schedule Jobs</a>
					<ul>
						<li><a href="ScheduleMonitor.html">Monitor Schedules</a></li>
					</ul>
				</li>
			    	<li><a href="#" class="fly">Masters</a>
					<ul>
						<li><a href="ListAllMasters.html">View Masters</a></li>
						<li><a href="CreateMasters.html">Add Masters</a></li>
						<li><a href="ListAllFeedFormats.html">Feed Format</a></li>
						<li><a href="ListAllFeedSch.html">Schedule Feed Upload</a></li>
					</ul>
			    	</li>
			    	<li><a href="#" class="fly">Products</a>
					<ul>
					    <li><a href="ListAllProducts.html">View Products</a></li>
					    <li><a href="#">View History</a></li>
					</ul>
			    	</li>
			    	<li><a href="#" class="fly">Expiry</a>
					<ul>
					    <li><a href="#">Add Notification Template</a></li>
					    <li><a href="#">Add Notification Rules </a></li>
					    <li><a href="#">View Results</a></li>
					</ul>
			    	</li>
                                <li><a href="#" class="fly">Survey</a>
                                        <ul>
                                            <li><a href="#">View Survey</a></li>
                                            <li><a href="#">Edit Survey</a></li>
                                            <li><a href="#">Setup Survey</a></li>
                                            <li><a href="#">Results</a></li>
                                        </ul>
                                </li>
                                <li><a href="#" class="fly">Opinion poll</a>
                                        <ul>
                                            <li><a href="#">View Opinion poll</a></li>
                                            <li><a href="#">Edit Opinion poll</a></li>
                                            <li><a href="#">Setup Opinion poll</a></li>
                                            <li><a href="#">Results</a></li>
                                        </ul>
                                </li>
                                <li><a href="#" class="fly">Lottery</a>
                                        <ul>
                                            <li><a href="#">View Lottery</a></li>
                                            <li><a href="#">Edit Lottery</a></li>
                                            <li><a href="#">Setup Lottery</a></li>
                                            <li><a href="#">Results</a></li>
                                        </ul>
                                </li>
                            	</ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">MEMBERS</span></a>
				<ul class="sub">
                                    <li><a href="#" class="fly">Manage Member</a>
                                        <ul>
                                            <li><a href="ListAllMembers.html">View Members</a></li>
                                            <li><a href="CreateMember.html">Add Members</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Membership Fee</a>
                                        <ul>
                                            <li><a href="ListAllMemberFee.html">View Membership Fee</a></li>
                                            <li><a href="CreateMemberFee.html">Add Membership Fee</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Manage Membership</a>
                                        <ul>
                                            <li><a href="ListAllMembership-Renew.html">Renew Membership</a></li>
                                            <li><a href="#">Cancel Membership</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Manage Referral</a>
                                        <ul>
                                            <li><a href="#">Setup Referral Rules</a></li>
                                            <li><a href="#">View Referral Transactions</a></li>
                                        </ul>
                                    </li>
                               	</ul>
                             </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">SCHEME </span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">Schemes</a>
                                        <ul>
                                            <li><a href="ListAllSchemes.html">View Schemes</a></li>
                                            <li><a href="CreateScheme.html">Add Schemes</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Criteria</a>
                                        <ul>
                                            <li><a href="ListAllCriteria.html">View Criteria</a></li>
                                            <li><a href="AddCriteria.html">Add Criteria</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Rules</a>
                                        <ul>
                                            <li><a href="ListAllRules.html">View Rules</a></li>
                                            <li><a href="Add rules.html">Add Rules</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Purchase</a>
                                        <ul>
                                            <li><a href="#">Buy</a></li>
                                            <li><a href="#">Sell</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Expiry</a>
                                        <ul>
                                            <li><a href="#">Near Expiry Rewards</a></li>
                                            <li><a href="#">Expired Rewards</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">REDEMPTIONS</span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">Transactions</a>
                                        <ul>
                                            <li><a href="View-Redemption.html">Customer Redemptions</a></li>
                                            <li><a href="View-Redemption-Partner.html">Partner Redemptions</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Balance</a>
                                        <ul>
                                            <li><a href="#">Search Customer</a></li>
                                            <li><a href="#">View Balanace</a></li>
                                            <li><a href="#">Add Redemption</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Transfer</a>
                                        <ul>
                                            <li><a href="#">View Transfer Status</a></li>
                                            <li><a href="#">Edit Transfer</a></li>
                                            <li><a href="#">Add Transfer</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Cancel</a>
                                        <ul>
                                            <li><a href="#">Search Redemptions</a></li>
                                            <li><a href="#">Cancel Redemptions</a></li>
                                            <li><a href="#">Re-Assign Redemptions</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">PARTNERS</span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">Manage</a>
                                        <ul>
                                            <li><a href="#">Search Partner</a></li>
                                            <li><a href="#">Edit Partner</a></li>
                                            <li><a href="#">Add Partner</a></li>
                                            <li><a href="#">Partner Contract</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Products</a>
                                        <ul>
                                            <li><a href="#">View Products</a></li>
                                            <li><a href="#">Add Products</a></li>
                                            <li><a href="#">Edit Products</a></li>
                                            <li><a href="#">Approved Products</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Payment</a>
                                        <ul>
                                            <li><a href="#">View Payment</a></li>
                                            <li><a href="#">Release Payment</a></li>
                                            <li><a href="#">Payment History</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Cancel</a>
                                        <ul>
                                            <li><a href="#">Search Redemptions</a></li>
                                            <li><a href="#">Cancel Redemptions</a></li>
                                            <li><a href="#">Re-Assign Redemptions</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="top"><a class="top_link" href="#"><span class="down">REPORTS</span></a>
								<ul class="sub">
                                    <li><a href="#" class="fly">Rewards</a>
                                        <ul>
                                            <li><a href="#">Summary Report</a></li>
                                            <li><a href="#">Scheme Analysis</a></li>
                                            <li><a href="#">Expired Report</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Redemption</a>
                                        <ul>
                                            <li><a href="#">Summary Report</a></li>
                                            <li><a href="#">Cancelation Report</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="fly">Partners</a>
                                        <ul>
                                            <li><a href="#">Summary Report</a></li>
                                            <li><a href="#">Reconciliation Report</a></li>
                                            <li><a href="#">Cancelation Report</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>