<ul>
	<li>Details
		<ul>
			<li><a href="AptDetailsView.html">View Details</a></li>
		</ul>
	</li>
	<li>Flat Details
		<ul>
			<li><a href="ListAllFlats.html">View Details</a></li>
		</ul>
	</li>
	<li>Monthly Charges
		<ul>
			<li><a href="AptMonthlyCharges.html">View Details</a></li>
		</ul>
	</li>
	<li>Common Rentals
		<ul>
			<li><a href="#">View Details</a></li>
		</ul>
	</li>
	<li>Calculation
		<ul>
			<li><a href="#">View Calcuation Setup</a></li>
		</ul>
	</li>
</ul>
