<div>
	<ul id="nav">
		<li class="top"><a class="top_link" href="#"><span class="down">Administration</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">User Management</a>
					<ul>
						<li><a href="ListAllUsers.html">View User </a></li>
						<li><a href="CreateUser.html">Add User </a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="top"><a class="top_link" href="#"><span class="down">Apartment</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">Details</a>
					<ul>
						<li><a href="AptDetailsView.html">View Details</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Flat Details</a>
					<ul>
						<li><a href="ListAllFlats.html">View Details</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Monthly Charges</a>
					<ul>
						<li><a href="AptMonthlyCharges.html">View Details</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Common Rentals</a>
					<ul>
						<li><a href="#">View Details</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Calculation</a>
					<ul>
						<li><a href="#">View Calcuation Setup</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="top"><a class="top_link" href="#"><span class="down">My Portfolio</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">My Details</a>
					<ul>
						<li><a href="PersonalDetails.html">View Details</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Flat Details</a>
					<ul>
						<li><a href="#">View Details</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Payment</a>
					<ul>
						<li><a href="#">View Payment</a></li>
						<li><a href="#">Add Payment Details</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="top"><a class="top_link" href="#"><span class="down">Info Center</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">Meeting Minutes</a>
					<ul>
						<li><a href="ViewMeetingMinutes.html">View Minutes</a></li>
						<li><a href="#">Add Minutes</a></li>
						<li><a href="#">Initiation Request</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">General Info</a>
					<ul>
						<li><a href="#">View Apartment Details</a></li>
						<li><a href="#">Add General Info</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="top"><a class="top_link" href="#"><span class="down">Reports</span></a>
			<ul class="sub">
				<li><a href="#" class="fly">Expenses</a>
					<ul>
						<li><a href="ReportsExpenses.html">Expense Report</a></li>
					</ul>
				</li>
				<li><a href="#" class="fly">Payment</a>
					<ul>
						<li><a href="#">Payment Report</a></li>
					</ul>
				</li>
			</ul>
		</li>
	</ul>
</div>